url: https://spatlyu.github.io/geocomplexity/
template:
  bootstrap: 5
  bootswatch: spacelab
on:
  push:
    branches: main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
    - name: Install dependencies
      run: |
        install.packages('remotes')
        remotes::install_deps(dependencies = TRUE)
        remotes::install_cran('pkgdown')
    - name: Build site
      run: |
        Rscript -e 'pkgdown::build_site()'
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
home:
  title: |
    geocomplexity | Geocomplexity mitigates spatial bias
authors:
  Wenbo Lv:
    href: https://spatlyu.github.io/
  Yongze Song:
    href: https://yongzesong.com/

